[project]
name = "langchain-for-llm-apps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipykernel>=6.29.5",
    "openai>=1.61.0",
    "python-dotenv>=1.0.1",
]
